FileCloudStorageLiberary/TestWeb/Controllers/DropBoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Hosting;
using TestWeb.ViewModel;
using TestWeb.Model;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using Microsoft.Net.Http.Headers;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TestWeb.Controllers
{
    public class DropBoxController : Controller
    {
        IHostingEnvironment _enviroment;
        public DropBoxController(IHostingEnvironment env)
        {
            _enviroment = env;
        }
        public DropBoxVM DBVM { get; set; }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Authorize()
        {
            DBVM = new DropBoxVM();
            DBVM.SetRedirectUri("http://localhost:5000/DropBox/AuthorizeResult/");
            string uri = DBVM.GeefUri();
            return Redirect(uri);
        }


        [HttpGet]
        public IActionResult AuthorizeResult(string code, string state)
        {

            var jsonResp = FileCloudStorageLiberary.DropBox.GetAccesToken(code, "http://localhost:5000/DropBox/AuthorizeResult/");
            string url =string.Format( "http://localhost:5000/DropBox/AcountPage?access_token={0}&bearer={1}&uid{2}", jsonResp["access_token"], jsonResp["token_type"], jsonResp["uid"]);
            return Redirect(url);
            
        }


       

       

        public async Task<IActionResult> AcountPage(string access_token, string bearer,string uid)
        {
            DBVM = new DropBoxVM();
            DBVM.AccesToken = access_token;
           HttpContext.Session.SetString("access_token", access_token);
            await DBVM.logIn();
            ViewData["OnSucces"] = false;
            return View(DBVM.MyAccount);
        }

        [HttpPost]
        public async Task<IActionResult> AcountPage(ICollection<IFormFile> files)
        {
            DBVM = new DropBoxVM();
            DBVM.AccesToken = HttpContext.Session.GetString("access_token");
            await DBVM.logIn();
            var path = Path.Combine(_enviroment.WebRootPath, "uploaded");
            foreach (var file in files)
            {
                if(file.Length >0)
                {
                    var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    var filepath = Path.Combine(path, @filename);
                    await file.SaveAsAsync(filepath);
                    await DBVM.UploadFile(filepath);
                    System.IO.File.Delete(filepath);

                }

            }
             ViewData["OnSucces"] = true;
            return View();

        }



    }
}

FileCloudStorageLiberary/TestWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace TestWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

FileCloudStorageLiberary/TestWeb/Controllers/googleCloudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Hosting;
using System.IO;
using Microsoft.Net.Http.Headers;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TestWeb.Controllers
{
    public class googleCloudController : Controller
    {
        IHostingEnvironment _enviroment;
        public googleCloudController(IHostingEnvironment env)
        {
            _enviroment = env;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetCode()
        {
            FileCloudStorageLiberary.GoogleDrive drive = new FileCloudStorageLiberary.GoogleDrive();
            return Redirect(drive.GetAuthCodeUrl("http://localhost:5000/googleCloud/Auth2CallBack"));

        }

        public IActionResult Auth2CallBack(string code)
        {

            Dictionary<string, string> waardes = FileCloudStorageLiberary.GoogleDrive.GetAccesToken(code, "http://localhost:5000/googleCloud/Auth2CallBack");
            foreach(var key in waardes.Keys)
            {
                HttpContext.Session.SetString(key, waardes[key]);
            }
            
            return RedirectToAction("UploadFile");
        }

        public IActionResult UploadFile()
        {
            var parentId = FileCloudStorageLiberary.GoogleDrive.MaakCloudFolder(HttpContext.Session.GetString("access_token"));
            HttpContext.Session.SetString("ParentId", parentId);
            var lijst = FileCloudStorageLiberary.GoogleDrive.GetList(HttpContext.Session.GetString("access_token"), parentId);
            return View(lijst);

        }
        [HttpPost]
        public async Task<IActionResult> UploadFile(IEnumerable<IFormFile> files)
        {
            
            var path = Path.Combine(_enviroment.WebRootPath, "uploaded");
            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    var filepath = Path.Combine(path, @filename);
                    await file.SaveAsAsync(filepath);
                    FileCloudStorageLiberary.GoogleDrive.UploadFile(HttpContext.Session.GetString("access_token"), filepath, file.ContentType, filename, HttpContext.Session.GetString("ParentId"));
                  
                    System.IO.File.Delete(filepath);

                }

            }
            var lijst = FileCloudStorageLiberary.GoogleDrive.GetList(HttpContext.Session.GetString("access_token"),HttpContext.Session.GetString("ParentId"));
            return View(lijst);
        }


    }
}

FileCloudStorageLiberary/TestWeb/Views/DropBox/AcountPage.cshtml
@model TestWeb.Model.Acount
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<html>
<head>


</head>
<body>
    <div>
    @Html.LabelFor(p => p.Name);
    @Html.TextBoxFor(p => p.Name);
</div>
    <div>
        @Html.LabelFor(p => p.Email);
        @Html.TextBoxFor(p => p.Email);
    </div>

    <form method="post" asp-action="AcountPage" asp-controller="DropBox" enctype="multipart/form-data">
        <input type="file" name="files" multiple />
        <input type="submit" value="Upload" />
    </form>

    @if((bool)ViewData["OnSucces"])
    {

        <label>Succesfully Uploaded</label>
    }
</body>

</html>

FileCloudStorageLiberary/TestWeb/Views/DropBox/AuthorizeResult.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string accestoken = "";
}

<head>
<script>

    window.onload = function()
    {
        if( window.location.hash)
        {
            accestoken = window.location.hash.substring(1);
            window.location.href = "http://localhost:5000/DropBox/AcountPage?" + accestoken;
        }


    }


</script>
    </head>

FileCloudStorageLiberary/TestWeb/Views/DropBox/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<html>



<body>

    <button> @Html.ActionLink("Authenticate DropBox", "Authorize", "Dropbox")  </button>


</body>



</html>

FileCloudStorageLiberary/TestWeb/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

FileCloudStorageLiberary/TestWeb/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FileCloudStorageLiberary/TestWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/ASP-NET-Banners-01.png" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Banner-02-VS.png" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/ASP-NET-Banners-02.png" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Banner-01-Azure.png" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET MVC 6</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699314">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET 5</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET 5 such as Startup and middleware.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517852">Run your app on .NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run commands in your project.json</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

FileCloudStorageLiberary/TestWeb/Views/OneDrive/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<html>

<body>

    <div style="margin:20px">
        @Html.ActionLink("Authenticate", "AuthCode","OneDrive")
    </div>

</body>

</html>

FileCloudStorageLiberary/TestWeb/Views/OneDrive/OverView.cshtml
@model FileCloudStorageLiberary.OneDriveAccount

<html>

<body>

    <div>
        @Html.LabelFor(p => p.name)
        <label>@Model.name</label>
    </div>

    <div>
        @Html.LabelFor(p=>p.locale,"locatie")
        <label>@Model.locale</label>

    </div>

    <img src=@Model.picture />

     @Html.ActionLink("Files", "UploadFile", "OneDrive")
</body>


</html>

FileCloudStorageLiberary/TestWeb/Views/OneDrive/UploadFile.cshtml
@model FileCloudStorageLiberary.OneDriveModels.FileLijstOneDrive


<html>

<body>

    <ul>
        @foreach (var item in Model.value)
        {
            <li>
                <label>@item.name</label>
                <label>@item.file.mimeType</label>
            </li>
        }

    </ul>

    <div style="margin:30px">
        <form method="post" asp-action="UploadFile" asp-controller="OneDrive" enctype="multipart/form-data">
            <input type="file" name="files" multiple />
            <input type="submit" value="Upload" />
        </form>


    </div>
</body>

</html>

FileCloudStorageLiberary/TestWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWeb</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">TestWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="OneDrive" asp-action="Index">One Drive</a></li>
                    <li><a asp-controller="googleCloud" asp-action="Index">Google Drive</a></li>
                    <li><a asp-controller="DropBox" asp-action="Index">Drop Box</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - TestWeb</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

FileCloudStorageLiberary/TestWeb/Views/googleCloud/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<html>


<body>
    <div style="margin:20px">
        @Html.ActionLink("Authorize", "GetCode", "googleCloud")
    </div>

</body>
</html>

FileCloudStorageLiberary/TestWeb/Views/googleCloud/UploadFile.cshtml
@model List<string>
   



<html>

   

           <body>
               <div>
                   <ul>
    @foreach (var p in Model)
    {

        <li> <label>@p</label></li>
        }
    </ul>


               </div>
            <div style="margin:20px">
                <form method="post" asp-action="UploadFile" asp-controller="googleCloud" enctype="multipart/form-data">
                    <input type="file" name="files" multiple />
                    <input type="submit" value="Upload" />
                </form>

            </div>


           </body>


</html>